import type { APIRoute } from "astro";

export const prerender = true;

// build-data.json is generated by build:mock or build:export scripts.
// Import directly like other prerendered pages do.
let buildData: { domains?: { public?: string } } | null = null;
try {
  const { default: data } = await import("../data/build-data.json");
  if (data) buildData = data;
} catch { /* build-data.json not generated yet */ }

export const GET: APIRoute = async ({ site }) => {
  let origin = site?.href.replace(/\/$/, "") || "https://yourcompany.com";

  if (buildData?.domains?.public) {
    origin = `https://${buildData.domains.public.replace(/^https?:\/\//, "").replace(/\/.*$/, "")}`;
  }

  const robotsTxt = `User-agent: *
Allow: /

Disallow: /admin/
Disallow: /api/
Disallow: /login

Sitemap: ${origin}/sitemap.xml
`;

  return new Response(robotsTxt, {
    headers: { "Content-Type": "text/plain" },
  });
};
