#!/usr/bin/env node

/**
 * Inject theme overrides from build-data.json into CSS custom properties.
 *
 * Usage:
 *   node scripts/inject-theme.mjs
 *
 * Output: src/styles/theme-overrides.css
 *
 * This script reads theme settings from build-data.json and generates
 * a CSS file that overrides the default :root tokens in global.css.
 * If no theme settings are found, an empty file is generated (no overrides).
 *
 * Supported theme settings (stored in site_settings):
 *   - theme_brand_color: hex color for --color-brand-600 (primary brand color)
 *   - theme_font_family: font family string for --font-sans
 *
 * The script auto-generates the full brand palette (50-900) from a single
 * brand color using HSL manipulation.
 */

import { writeFileSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ── Read build-data.json ──────────────────────────
let buildData = null;
try {
  const raw = readFileSync(resolve(ROOT, 'src/data/build-data.json'), 'utf-8');
  buildData = JSON.parse(raw);
} catch {
  console.log('[inject-theme] No build-data.json found, generating empty overrides.');
  writeFileSync(resolve(ROOT, 'src/styles/theme-overrides.css'), '/* Theme overrides — no custom theme configured */\n');
  process.exit(0);
}

const settings = buildData.settings || {};
const brandColor = settings.theme_brand_color || '';
const fontFamily = settings.theme_font_family || '';

// ── Color utilities ───────────────────────────────
function hexToHSL(hex) {
  hex = hex.replace('#', '');
  if (hex.length === 3) hex = hex.split('').map(c => c + c).join('');
  const r = parseInt(hex.substring(0, 2), 16) / 255;
  const g = parseInt(hex.substring(2, 4), 16) / 255;
  const b = parseInt(hex.substring(4, 6), 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h = 0, s = 0, l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
      case g: h = ((b - r) / d + 2) / 6; break;
      case b: h = ((r - g) / d + 4) / 6; break;
    }
  }
  return { h: Math.round(h * 360), s: Math.round(s * 100), l: Math.round(l * 100) };
}

function hslToHex(h, s, l) {
  s /= 100; l /= 100;
  const a = s * Math.min(l, 1 - l);
  const f = n => {
    const k = (n + h / 30) % 12;
    const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
    return Math.round(255 * color).toString(16).padStart(2, '0');
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}

/**
 * Generate a full brand palette (50-900) from a single base color.
 * Uses HSL manipulation to create lighter and darker variants.
 */
function generateBrandPalette(baseHex) {
  const { h, s } = hexToHSL(baseHex);
  return {
    50:  hslToHex(h, Math.min(s + 10, 100), 97),
    100: hslToHex(h, Math.min(s + 10, 100), 94),
    200: hslToHex(h, Math.min(s + 5, 100), 86),
    300: hslToHex(h, Math.min(s, 100), 74),
    400: hslToHex(h, s, 58),
    500: hslToHex(h, s, 48),
    600: baseHex,  // The user-specified color
    700: hslToHex(h, Math.min(s + 5, 100), 36),
    800: hslToHex(h, Math.min(s + 10, 100), 28),
    900: hslToHex(h, Math.min(s + 10, 100), 22),
  };
}

// ── Generate CSS ──────────────────────────────────
const lines = ['/* Theme overrides — auto-generated by scripts/inject-theme.mjs */', ''];

if (brandColor) {
  // Validate hex format
  if (!/^#[0-9a-fA-F]{3,6}$/.test(brandColor)) {
    console.warn(`[inject-theme] Invalid theme_brand_color: "${brandColor}" (expected hex like #059669). Skipping.`);
  } else {
    const palette = generateBrandPalette(brandColor);
    lines.push(':root {');
    for (const [level, hex] of Object.entries(palette)) {
      lines.push(`  --color-brand-${level}: ${hex};`);
    }
    lines.push('}');
    lines.push('');
  }
}

if (fontFamily) {
  lines.push(':root {');
  lines.push(`  --font-sans: ${fontFamily};`);
  lines.push('}');
  lines.push('');
}

if (!brandColor && !fontFamily) {
  lines.push('/* No custom theme configured — using defaults from global.css */');
}

const css = lines.join('\n') + '\n';
const outPath = resolve(ROOT, 'src/styles/theme-overrides.css');
writeFileSync(outPath, css, 'utf-8');

console.log(`[inject-theme] Written to ${outPath}`);
if (brandColor) console.log(`  Brand color: ${brandColor} (palette generated)`);
if (fontFamily) console.log(`  Font family: ${fontFamily}`);
if (!brandColor && !fontFamily) console.log(`  No theme overrides (using defaults)`);
