-- Seed admin user via SQL
-- Run: npx wrangler d1 execute DB --local --file=./scripts/seed-admin.sql
--
-- PREREQUISITES:
--   1. Create the admin user via the API or seed-admin.mjs script first
--      (which handles password hashing via Better Auth)
--   2. Then use this script ONLY to set the role if needed:
--      UPDATE users SET role = 'admin' WHERE email = 'your-admin@example.com';
--
-- WARNING: Do NOT insert users directly via SQL — passwords must be
-- hashed by Better Auth's bcrypt implementation. Use seed-admin.mjs instead.

-- Set admin role for an existing user (replace email with actual admin email)
-- UPDATE users SET role = 'admin' WHERE email = 'your-admin@example.com';
